name = "tasks-app"
main = "worker/index.js"
compatibility_date = "2026-10-07"

[assets]
directory = "./prototype"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "tasks"
database_id = "961be54d-150c-41cc-bd9f-21899ccc12db"
